# Generated by Django 3.2.4 on 2021-06-15 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shuksys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbu', models.BigIntegerField()),
                ('numeroEntidad', models.IntegerField()),
                ('numeroSucursal', models.IntegerField()),
                ('numerocuenta', models.BigIntegerField()),
                ('idBanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuksys.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPedido', models.DateTimeField(auto_now=True)),
                ('numeroSeguimiento', models.CharField(max_length=255, null=True)),
                ('fechaDespacho', models.DateTimeField(default=None, null=True)),
                ('idDetalleVenta', models.IntegerField()),
                ('comentario', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuksys.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='producto',
            name='idProductoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuksys.productocategoria'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuksys.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idPedidoEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuksys.pedidoestado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
