# Generated by Django 3.2.4 on 2021-06-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0002_auto_20210615_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProductoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='shuksys.productocategoria'),
        ),
    ]
