# Generated by Django 3.2.4 on 2021-06-22 22:26

from django.db import migrations, models
import django.db.models.deletion
import rest_framework.mixins
import rest_framework.viewsets


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('shuksys', '0003_alter_producto_idproductocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCategoriaViewSet',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
            ],
            bases=(rest_framework.viewsets.GenericViewSet, rest_framework.mixins.ListModelMixin, 'authtoken.token'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idDetalleVenta',
            field=models.IntegerField(null=True),
        ),
    ]
