# Generated by Django 3.2.4 on 2021-06-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0004_auto_20210622_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDesde', models.DateField(null=True)),
                ('fechaHasta', models.DateField(null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='idLote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shuksys.lote'),
            preserve_default=False,
        ),
    ]
