# Generated by Django 3.2.4 on 2021-06-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0005_auto_20210623_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idLote',
            field=models.IntegerField(),
        ),
    ]
