# Generated by Django 3.2.4 on 2021-06-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0006_alter_pedido_idlote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idLote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuksys.lote'),
        ),
    ]
