# Generated by Django 3.2.4 on 2021-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0007_alter_pedido_idlote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idDetalleVenta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numeroSeguimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
