# Generated by Django 3.2.9 on 2022-01-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0008_auto_20210623_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
