# Generated by Django 3.2.9 on 2022-03-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0009_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idPedidoEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='shuksys.pedidoestado'),
        ),
    ]
