# Generated by Django 3.2.9 on 2022-03-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0010_alter_pedido_idpedidoestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='horaPedido',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechaDespacho',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechaPedido',
            field=models.DateField(auto_now=True),
        ),
    ]
