# Generated by Django 3.2.9 on 2022-04-15 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0012_alter_pedido_fechadespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='idPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='shuksys.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='shuksys.producto'),
        ),
    ]
