# Generated by Django 3.2.9 on 2022-04-16 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0013_auto_20220415_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuksys.producto'),
        ),
    ]
