# Generated by Django 3.2.9 on 2022-05-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuksys', '0014_alter_pedidodetalle_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idLote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shuksys.lote'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idPedidoEstado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='shuksys.pedidoestado'),
        ),
    ]
